# Generated by Django 4.0.4 on 2023-02-11 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmwork',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='created_date')),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='rating')),
                ('type', models.CharField(choices=[('movie', 'movie'), ('tv_show', 'tv_show')], default='movie', max_length=7, verbose_name='types')),
            ],
            options={
                'db_table': 'content"."filmwork',
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='notification_group_name')),
            ],
            options={
                'db_table': 'content"."notificationgroup',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='template_name')),
                ('template', models.TextField(blank=True, null=True, verbose_name='template')),
                ('type', models.CharField(choices=[('email', 'email'), ('push', 'push'), ('sms', 'sms')], default='email', max_length=5)),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=6)),
            ],
            options={
                'db_table': 'content"."template',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255, null=True, verbose_name='fullname')),
                ('login', models.CharField(max_length=63, verbose_name='login')),
                ('password', models.TextField(blank=True, null=True, verbose_name='password')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_email')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='user_phone')),
                ('allow_send_email', models.BooleanField(default=False, verbose_name='allow_send_email')),
                ('confirmed_email', models.BooleanField(default=False, verbose_name='confirmed_email')),
            ],
            options={
                'db_table': 'content"."user',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.notificationgroup', verbose_name='notification_group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.user', verbose_name='user')),
            ],
            options={
                'db_table': 'content"."UserNotificationUserGroup',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='notification_group',
            field=models.ManyToManyField(through='movies.UserNotificationGroup', to='movies.notificationgroup', verbose_name='notification_group_name'),
        ),
        migrations.AddConstraint(
            model_name='usernotificationgroup',
            constraint=models.UniqueConstraint(fields=('user', 'notification_user_group'), name='user_notification_user_group_idx'),
        ),
    ]
