# Generated by Django 4.0.4 on 2023-02-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.IntegerField(default=0, verbose_name='timezone'),
        ),
    ]
