# Generated by Django 4.0.4 on 2023-02-11 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template', models.TextField(blank=True, null=True, verbose_name='template')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=63, verbose_name='login')),
                ('password', models.TextField(blank=True, null=True, verbose_name='password')),
                ('fullname', models.CharField(max_length=127, null=True, verbose_name='fullname')),
                ('email', models.CharField(max_length=63, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=31, null=True, verbose_name='phone')),
                ('subscribed', models.BooleanField(default=False, verbose_name='subscribed')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
