# Generated by Django 4.0.4 on 2023-02-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_user_timezone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationgroup',
            options={'verbose_name': 'notification_group', 'verbose_name_plural': 'notification_groups'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'template', 'verbose_name_plural': 'templates'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='usernotificationgroup',
            options={'verbose_name': 'user_notification_group', 'verbose_name_plural': 'user_notification_groups'},
        ),
    ]
