name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  quality_code:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide flake8-html mypy lxml

      - name: Create reports folders
        run: |
          mkdir -p reports/wemake/
          mkdir -p reports/mypy/

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --exit-zero --max-complexity=10 --max-line-length=127 --format=html --htmldir=reports/wemake/

      - name: Lint with mypy
        run: |
          mypy . --html-report reports/mypy/

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: reports/

  unit_tests:

    needs: ["quality_code"]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python_version: [ "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r admin_panel/tests/requirements.txt
        pip install -r notification_api/tests/requirements.txt`
        if [ -f admin_panel/requirements.txt ]; then pip install -r admin_panel/requirements.txt; fi
        if [ -f notification_api/requirements.txt ]; then pip install -r notification_api/requirements.txt; fi

    - name: Test with pytest admin_panel
      run: |
        pytest admin_panel/tests/unit

    - name: Test with pytest notification_api
      run: |
        pytest notification_api/tests/unit